import React, { ReactNode } from 'react'
import type { Metadata } from 'next'
import BreadcrumbComponent from '@/components/breadcrumb.component'

export const metadata: Metadata = {
    title: 'Mangasi - Collections',
    description: 'Generated by create next app',
  }

export default function layout({children}:{children:ReactNode}) {
  return (
    <div className="w-full relative">
      <BreadcrumbComponent />
    <section>
      
    <div className="flex flex-col gap-4">
        {children}
        </div>
    </section>
  </div>
  )
}
